In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.zeros((3,3))

In [142]:
A[2,0] = 1
A[2,1] = 1

gamma = 0.9

tau = 1e5

eta = (1-gamma)**2/(tau**1)*1e-1
# eta = 1e-5
C = 1

alpha = 1-eta*tau/(1-gamma)
# factor = tau
factor = 1

A[0,0] = gamma*(1-alpha)+eta*tau*C/(1-gamma)**2/factor
A[0,1] = gamma*alpha + (1-gamma-eta*tau)*C/(1-gamma)**2/factor
A[0,2] = gamma - gamma*eta*tau/(1-gamma) - gamma*eta**2*tau**2*C/(1-gamma)**3
A[1,0] = eta*tau/(1-gamma)
A[1,1] = 1-eta*tau/(1-gamma)

print(A)
print(np.max(np.abs(np.linalg.eigvals(A))))
print((np.linalg.eig(A)[1]))



[[1.0900e-01 1.0791e+01 8.9010e-01]
 [1.0000e-02 9.9000e-01 0.0000e+00]
 [1.0000e+00 1.0000e+00 0.0000e+00]]
1.254137579952392
[[ 0.67704642 -0.77008129  0.62187094]
 [-0.00355376 -0.02915455 -0.02704008]
 [-0.73593174 -0.63727924  0.78265277]]


In [29]:
print(np.linalg.eigvals(A))

[ 22899.64544582+322274.10697902j  22899.64544582-322274.10697902j
 -95798.29089164     +0.j        ]
