In [1]:
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
import copy

In [3]:
n=2
# action_spaces = np.array([3,4,5])
# action_spaces = np.array([3,3])
action_spaces = np.array([2,2])

reward = np.zeros(action_spaces)
reward = np.random.uniform(0,1,size=action_spaces)
# reward = np.array([[1,1],[0,1]])
# rewards = [reward]
# reward[0,1] = reward[1,2] = reward[2,0] = 1
# reward[1,0] = reward[2,1] = reward[0,2] = -1


print(reward)
# Start state distribution
# rho = np.ones(s) / s

# initial_pi = np.ones((n,a))/a
# initial_pi = ([np.array([1/i for x in range(int(i))]) for i in (action_spaces)])
initial_pi = ([np.random.uniform(0,1,size=int(i)) for i in (action_spaces)])
for pi in initial_pi:
    pi/=np.sum(pi)
print(initial_pi)



[[0.03522304 0.76491502]
 [0.85096166 0.97674478]]
[array([0.94116587, 0.05883413]), array([0.25868143, 0.74131857])]


In [12]:
random_pi = np.random.uniform(0,1,size=action_spaces)
random_pi /= np.sum(random_pi)

In [19]:
print(random_pi)

pi1 = np.sum(random_pi, axis=0)
pi2 = np.sum(random_pi, axis=1)

print(pi1, pi2)

stack_pi = np.zeros(action_spaces)
for i in range(action_spaces[0]):
    for j in range(action_spaces[1]):
        stack_pi[i,j]+= pi1[i]*pi2[j]
print(stack_pi)
kl1 = 0
kl2 = 0

for prob in pi1:
    kl1+= -prob*np.log(prob)
    
for prob in pi2:
    kl2+= -prob*np.log(prob)
    
print(kl1, kl2, kl1 + kl2)

    
total_kl = 0
stack_kl = 0
for i in range(action_spaces[0]):
    for j in range(action_spaces[1]):
        total_kl+= -random_pi[i,j]*np.log(random_pi[i,j])
        stack_kl+= -stack_pi[i,j]*np.log(stack_pi[i,j])
        
print(total_kl, stack_kl)
    

[[0.22375057 0.12316262]
 [0.5631607  0.08992611]]
[0.78691127 0.21308873] [0.34691319 0.65308681]
[[0.2729899  0.51392137]
 [0.07392329 0.13916544]]
0.5180203580016667 0.6455148130969588 1.1635351710986255
1.1329102934679014 1.1635351710986255
